// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Malt.PasswordHasher")]
[assembly: AssemblyDescriptionAttribute("IPasswordHasher implementation for Asp.Net Identity")]
[assembly: AssemblyProductAttribute("PasswordHasher")]
[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyFileVersionAttribute("1.0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.1.0";
    }
}
